### ISSUE TITLE
Can't open the font file or find the correct one

### ISSUE THREAD

**Issue by H4CKL0RD** [games50/pong#35]

**Comment by H4CKL0RD** [comment]
this is also a pic of my code

push = require 'push'

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

VIRTUAL_WIDTH = 432
VIRTUAL_HEIGHT = 243

function love.load ()
  love.graphics.setDefaultFilter('nearest', 'nearest')
  smallFont = love.graphics.newFont('font.TTF', 8)
  love.graphics.setFont(smallFont)
  push:setupScreen(VIRTUAL_WIDTH, VIRTUAL_HEIGHT, WINDOW_WIDTH, WINDOW_HEIGHT, {
    fullscreen = false,
    resizable = false,
    vsync = true,
  })
end

function love.keypressed(key)
  if key == 'escape' then
    love.event.quit()
  end
end

function love.draw()
    push:apply('start')
    love.graphics.clear(40, 45, 52, 255)
    love.graphics.printf('Hello Pong!', 0, 20, VIRTUAL_WIDTH, 'center')
    love.graphics.rectangle('fill', 10, 30, 5, 20)
    love.graphics.rectangle('fill', VIRTUAL_WIDTH - 10, VIRTUAL_HEIGHT - 50, 5, 20)
    love.graphics.rectangle('fill', VIRTUAL_WIDTH / 2 - 2, VIRTUAL_HEIGHT / 2 - 2, 4, 4)
    push:apply('end')
end

**Comment by Kafeedos** [comment]
[font.zip](https://github.com/games50/pong/files/4517042/font.zip)
replace your font file with this one and your replace your code with this
" smallFont = love.graphics.newFont('font.ttf', 8)"

i hope it helps

**Comment by H4CKL0RD** [comment]
Thx i figured it out before you commented but couldn't find the file so thx for the font

**Comment by NTDLS** [comment]
@H4CKL0RD is this Steven? I've been looking for you. Hit me up! 
http://networkdls.com/Page/View/Official/Make_Contact
