### ISSUE TITLE
"HELLO PONG" text position not accurate

### ISSUE THREAD

**Issue by rinklea** [games50/pong#36]
I have the exact code but still, my text position is completely inaccurate.
This is my screen with the text at the bottom right.
<img width="1283" alt="Screen Shot 2020-04-22 at 6 39 27 PM" src="https://user-images.githubusercontent.com/64031090/79985684-9b2d8a00-84c8-11ea-8ee5-85374fec5c46.png">

**Comment by Abhiab3012** [comment]
yeh i too have been facing the same problem

**Comment by dchung1234** [comment]
If you're using a mac with retina display make sure the defaults in push.lua for highdpi is set to false

**Comment by rinklea** [comment]
I tried this but it did not help. It gives an error saying R_HEIGHT (nil value) in initvalues

**Comment by dchung1234** [comment]
The push.lua file on this master branch (the exact copy you get from here) is not up-to-date with the current version of LOVE2D. There are several changes that needs to be made. I suggest checking out the pull requests made to this branch and check out their changes

**Comment by rinklea** [comment]
Ya thanks I did that and now it's working.
