### ISSUE TITLE
Paddle class errors

### ISSUE THREAD

**Issue by Datto6** [games50/pong#49]
At first, there is the attempt to call global 'Class' (a nil value), which is an error, and then there is the "Attempt to index local self(a number value)" which, if you run the exact code colton used, still appears. Requires an update.

**Comment by weber401** [comment]
if you haven't worked out , can you share screenshot?

**Comment by Tincloudly** [comment]
Ok I will do that On 28 May 2020 16:56, weber401 <notifications@github.com> wrote:
if you haven't worked out , can you share screenshot?
